# Generated by Django 6.0.1 on 2026-02-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('plaque_immatriculation', models.CharField(max_length=20, unique=True)),
                ('modele_voiture', models.CharField(default='Taxi', max_length=100)),
                ('photo_voiture', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_permis', models.CharField(blank=True, max_length=255, null=True)),
                ('est_actif', models.BooleanField(default=False)),
                ('est_en_ligne', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('derniere_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
