# Generated by Django 6.0.1 on 2026-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('telephone', models.CharField(max_length=20, unique=True, verbose_name='Téléphone')),
                ('plaque_immatriculation', models.CharField(blank=True, max_length=20, null=True, verbose_name="Plaque d'immatriculation")),
                ('photo_permis', models.FileField(blank=True, null=True, upload_to='permis/')),
                ('photo_voiture', models.FileField(blank=True, null=True, upload_to='voitures/')),
                ('est_actif', models.BooleanField(default=False, verbose_name='Abonnement Actif')),
                ('est_en_ligne', models.BooleanField(default=False, verbose_name='En Service (En ligne)')),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
