# Generated by Django 6.0.1 on 2026-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='photo_permis',
            field=models.FileField(blank=True, null=True, upload_to='chauffeurs/permis/'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='photo_voiture',
            field=models.FileField(blank=True, null=True, upload_to='chauffeurs/voitures/'),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='plaque_immatriculation',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
