# Generated by Django 6.0.1 on 2026-02-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chauffeur',
            options={'verbose_name': 'Chauffeur', 'verbose_name_plural': 'Chauffeurs'},
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='photo_permis',
            field=models.FileField(blank=True, null=True, upload_to='permis/', verbose_name='Photo du Permis'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='photo_voiture',
            field=models.FileField(blank=True, null=True, upload_to='voitures/', verbose_name='Photo de la Voiture'),
        ),
    ]
