# Generated by Django 6.0.1 on 2026-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chauffeur',
            name='photo_permis',
            field=models.FileField(blank=True, null=True, upload_to='permis/'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='photo_vehicule',
            field=models.FileField(blank=True, null=True, upload_to='vehicules/'),
        ),
    ]
