# Generated by Django 6.0.1 on 2026-02-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs', '0002_alter_chauffeur_options_alter_chauffeur_photo_permis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chauffeur',
            options={},
        ),
        migrations.RemoveField(
            model_name='chauffeur',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='date_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='est_actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='est_en_ligne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='nom_complet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='photo_permis',
            field=models.FileField(blank=True, null=True, upload_to='permis/'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='photo_voiture',
            field=models.FileField(blank=True, null=True, upload_to='voitures/'),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='plaque_immatriculation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chauffeur',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
